---
- name: configure pacman
  block:
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#Color'
        line: 'Color'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#UseSyslog'
        line: 'UseSyslog'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#TotalDownload'
        line: 'TotalDownload'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#CheckSpace'
        line: 'CheckSpace'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#ILoveCandy'
        line: 'ILoveCandy'
        insertafter: '# Misc options'
    - blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist

- name: Update lists and upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install reflector config file.
  copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/reflector.conf

- name: enable reflector service
  systemd:
    name: reflector
    enabled: yes
    daemon_reload: no

#  TODO: See if we can run reflector manually in case it's never been run.
- name: enable reflector timer
  systemd:
    name: reflector.timer
    state: started
    enabled: yes
    daemon_reload: no

- name: Install pacman hooks
  become: no
  aur:
    name:
      - kernel-modules-hook # keep kernel modules dir after an upgrade
    skip_installed: true

- name: Install archaudit hook
  copy:
    src: arch-audit.hook
    dest: /usr/share/libalpm/hooks
