---
- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - mako # notification daemon
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - brightnessctl # brightness manager
      - swayidle
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-intel
      - lib32-vulkan-intel
      - intel-media-driver
      - libva-utils
    state: present

- name: install audio packages
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - code # code editor
      - evince # pdf viewer
      - firefox
      - gimp # img editor
      - kolourpaint # img editor
      - shotwell # photo manager
      - lollypop # music player
      - lxappearance # theme manager
      - mpv # video player
      - thunar # file manager
      - openvpn
      - playerctl # music player cli controller
      - rdesktop # remote desktop client
      - steam # games manager
      - transmission-gtk # torrent downloader
      - texlive-bin # latex
      - texlive-core # latex
      - texlive-latexextra # latex
      - variety # random backgrounds
      - papirus-icon-theme # icon theme
      - x2goclient 
      - youtube-dl
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv '{{item}}'
  loop:
    - 4773BD5E130D1D45 # spotify
    - F4B432D5D67990E3 # wob

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - adapta-gtk-theme #https://github.com/Alexays/Waybar/issues/515
      - equilux-theme 
      - wdisplays-git # arandr for wayland
      - wf-recorder-git # screen recorder for wayland
      - grimshot-git # grim+slurp wrapper
      - wofi-hg # rofi for wayland
      - swaylock-fancy-git # locker for wayland
      - wob # bars for wayland
      - connman-gtk # connman gtk gui
      - gnome-ssh-askpass2 # ssh askpass gui
      - google-chrome
      - downgrade # package downgrader
      - lf # cli file manager
      - otf-font-awesome
      #- ttf-impallari-cabin-font # xelatex cv
      - pastel # color viewer
      - spotify # music player
      - tiny-irc-client-git
      - starleaf-breeze
      - zoom
